const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8');
const script=html.match(/<script>\s*([\s\S]*?)<\/script>/)[1];
const nodes=new Map(),storage=new Map(),timers=[];const node=id=>nodes.get(id)||nodes.set(id,{id,value:'',type:html.includes(`id="${id}" type="checkbox"`)?'checkbox':'number',checked:false,textContent:'',innerHTML:'',style:{},classList:{contains:()=>false,add(){},remove(){},toggle(){}},addEventListener(){},appendChild(){},checkValidity:()=>true,reportValidity(){}}).get(id);
const ctx={console,Date,Promise,encodeURIComponent,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{querySelector:s=>node(s.slice(1)),querySelectorAll:()=>[],getElementById:node,createElement:()=>({}),head:{appendChild(){}},body:{style:{}}},setTimeout:(fn)=>{timers.push(fn);return timers.length},clearTimeout(){},location:{reload(){}},navigator:{}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(script,ctx);
const run=s=>vm.runInContext(s,ctx);assert.equal(run('P.length'),18);assert(run('P.every(x=>decisionFor(x)!=="BUY")'));
assert.equal(run('decisionFor({...P[0],price_usd:profile.budget+1})'),'PASS');
assert.equal(run('decisionFor({...P[0],structural_status:"failed"})'),'PASS');
assert.equal(run('decisionFor({...P[0],legal_status:"failed"})'),'PASS');
assert.equal(run('decisionFor({...P[0],price_usd:1})'),'WATCH');
assert.equal(run('componentScores(P[0]).growth'),0);
run("$('#search').value='not-found-zzzz';render()");assert(node('grid').innerHTML.includes('Нет объектов'));
run("$('#search').value='';$('#p_area_min').value=100;$('#p_area_max').value=70;applyProfile()");assert.equal(run('profile.areaMin'),70);
run("$('#p_area_min').value=70;$('#p_area_max').value=90;$('#p_budget').value=50000;applyProfile()");assert(run('P.every(x=>decisionFor(x)==="PASS")'));
(async()=>{await assert.rejects(run('loadGoogle()'));run("localStorage.setItem('rei_gmaps_key','test');window.google={maps:{}};");assert(await run('loadGoogle()'));run("localStorage.removeItem('rei_gmaps_key')");await assert.rejects(run('loadGoogle()'));run("window.google=undefined;localStorage.setItem('rei_gmaps_key','test');gPromise=null;googleFailed=false");const promise=run('loadGoogle()');run('gm_authFailure()');await assert.rejects(promise);assert(run('googleFailed'));console.log('PASS: syntax, boot, 18 cards, budget, legal/structural failures, verification gate, scoring, empty results, invalid ranges, saved profile, absent/deleted/rejected Google key');})().catch(e=>{console.error(e);process.exit(1)});
